export const FETCH_PRODUCTS_CATEGORY_REQUEST = "FETCH_PRODUCTS_CATEGORY_REQUEST";
export const FETCH_PRODUCTS_CATEGORY_SUCCESS = "FETCH_PRODUCTS_CATEGORY_SUCCESS";
export const FETCH_PRODUCTS_CATEGORY_FAILURE = "FETCH_PRODUCTS_CATEGORY_FAILURE";