export const GET_SINGLE_PODUCTS_REQUEST = "GET_SINGLE_PODUCTS_REQUEST"
export const GET_SINGLE_PODUCTS_SUCCESS = "GET_SINGLE_PODUCTS_SUCCESS"
export const GET_SINGLE_PODUCTS_FAILURE = "GET_SINGLE_PODUCTS_FAILURE"